refactor network operations in NetworkMonitorPlugin (#105)
* refactor network operations in NetworkMonitorPlugin

refactors the network operations in the `NetworkMonitorPlugin` class
The changes include the introduction of a new method, `remove_subnet_route_from_router`, to handle the removal of subnet routes from a router

without removing the route, the network cleanup is raising the Exception

ConflictException: 409: Client Error for url: <url>, Router interface for subnet on router cannot be deleted, as it is required by one or more routes.

Change-Id: I7e35002ff2e471fe47601e9daea8cf77fe1a01df

* fixes in remove_extra_routes_from_router call

Added extra test cases remove_subnet_route_from_router method to make sure it works

Tested in UC dev

Change-Id: I140b8d1897e941e088cfebc9433b8cc317bd7cb1

* Add logging for submet, router get exceptions

Change-Id: I07cce45e92c8a08522994e6675ba5eeed184c37e