refactor network operations in NetworkMonitorPlugin
refactors the network operations in the `NetworkMonitorPlugin` class
The changes include the introduction of a new method, `remove_subnet_route_from_router`, to handle the removal of subnet routes from a router

without removing the route, the network cleanup is raising the Exception

ConflictException: 409: Client Error for url: <url>, Router interface for subnet on router cannot be deleted, as it is required by one or more routes.

Change-Id: I7e35002ff2e471fe47601e9daea8cf77fe1a01df